#!/usr/bin/env python3
"""Merge the legendary shared contract and piece briefs into standalone prompts.

`prompts/22_legendary_one_of_one.md` keeps the output contract in one place and
the seven briefs separate, which is right for editing — a rule that changes
should change once. It is wrong for use: it makes the operator assemble two
blocks by hand seven times, and a contract silently pasted without its brief, or
a brief without its contract, produces a plausible-looking image that breaks the
collection.

This resolves them into seven self-contained prompts, so each one is a single
copy-paste with nothing to assemble. Regenerate rather than editing the output:

    python scripts/build_legendary_prompts.py
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "prompts" / "22_legendary_one_of_one.md"
DEFAULT_OUT = ROOT / "prompts" / "batch_legendary.md"


def fenced_blocks(text: str) -> list[str]:
    return re.findall(r"```text\n(.*?)```", text, re.DOTALL)


def parse(text: str) -> tuple[str, list[tuple[str, str]]]:
    """Return (shared contract, [(heading, brief), ...])."""
    blocks = fenced_blocks(text)
    if not blocks:
        raise ValueError("no ```text blocks found in the source prompt")
    contract = blocks[0].rstrip()

    headings = re.findall(r"^### (Legendary \d+ — .+)$", text, re.MULTILINE)
    briefs = blocks[1:]
    if len(headings) != len(briefs):
        raise ValueError(
            f"{len(headings)} piece headings but {len(briefs)} briefs; they must pair up"
        )
    return contract, list(zip(headings, [b.rstrip() for b in briefs]))


def compose(contract: str, heading: str, brief: str) -> str:
    # The brief goes above the contract's closing instruction so the model reads
    # the subject before the constraints it must satisfy.
    marker = "Return one PNG only, with no explanatory text."
    body = contract.replace(marker, "").rstrip()
    return f"{body}\n\n{brief}\n\n{marker}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    contract, pieces = parse(SOURCE.read_text())

    lines = [
        "# DEMIGODS — legendary 1-of-1 prompts, fully resolved",
        "",
        f"{len(pieces)} self-contained prompts. Each is a single copy-paste with nothing to "
        "assemble — the shared output contract is already merged into every one.",
        "",
        f"Generated by `python scripts/build_legendary_prompts.py` from "
        f"`{SOURCE.relative_to(ROOT)}`. Do not edit by hand — regenerate.",
        "",
        "**Attach to every prompt:** `assets/base_bodies/base_body_001_neutral_master.png` "
        "and `docs/rig/rig_guide_1254.png`, as proportion references only.",
        "",
        "These are full-bleed opaque compositions, so every existing rig-gate mode fails them "
        "by design. Check instead: native 1254 x 1254, zero transparent pixels, figure within "
        "X 233-1021 and Y 129-1139, feet on Y 1139, and no text anywhere in frame. Do not run "
        "the global finish or the background depth pass over them.",
        "",
        "## Progress",
        "",
    ]
    lines += [f"- [ ] {heading}" for heading, _ in pieces]
    lines += ["", "---", ""]

    for heading, brief in pieces:
        lines.append(f"## {heading}\n")
        lines.append("```")
        lines.append(compose(contract, heading, brief))
        lines.append("```\n")

    args.out.write_text("\n".join(lines))
    print(f"Wrote {args.out.relative_to(ROOT)} with {len(pieces)} resolved prompt(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
